// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignAccountToOU(ctx context.Context, arg AssignAccountToOUParams) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateGroup(ctx context.Context, displayName string) (Group, error)
	CreateMembershipForUserAndGroup(ctx context.Context, arg CreateMembershipForUserAndGroupParams) error
	CreateOrUpdateCloudAccount(ctx context.Context, arg CreateOrUpdateCloudAccountParams) (CloudAccount, error)
	//------------------------------------------------------------------------------------------------------------------
	// Cloud Tenants
	//------------------------------------------------------------------------------------------------------------------
	CreateOrUpdateCloudTenant(ctx context.Context, arg CreateOrUpdateCloudTenantParams) (CloudTenant, error)
	CreateOrganizationalUnit(ctx context.Context, arg CreateOrganizationalUnitParams) (OrganizationalUnit, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (StandardTag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, id uuid.UUID) error
	DeleteGroup(ctx context.Context, id uuid.UUID) error
	DeleteOrganizationalUnit(ctx context.Context, id uuid.UUID) error
	DeleteScimAPIKey(ctx context.Context) error
	DeleteTag(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DropMembershipForGroup(ctx context.Context, groupID uuid.UUID) error
	DropMembershipForUserAndGroup(ctx context.Context, arg DropMembershipForUserAndGroupParams) error
	FindAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error)
	FindAPIKeysById(ctx context.Context, dollar_1 []uuid.UUID) ([]ApiKey, error)
	FindByUsername(ctx context.Context, username string) (User, error)
	FindCloudAccount(ctx context.Context, id uuid.UUID) (CloudAccount, error)
	FindCloudAccountByCloudAndTenant(ctx context.Context, arg FindCloudAccountByCloudAndTenantParams) (CloudAccount, error)
	FindOrganizationalUnit(ctx context.Context, id uuid.UUID) (OrganizationalUnit, error)
	FindScimAPIKey(ctx context.Context) (ApiKey, error)
	FindTag(ctx context.Context, id uuid.UUID) (StandardTag, error)
	GetAPIKeys(ctx context.Context) ([]ApiKey, error)
	GetAPIKeysOrganizationalUnits(ctx context.Context, apiKeyID uuid.UUID) ([]OrganizationalUnit, error)
	//------------------------------------------------------------------------------------------------------------------
	// Audit Logs
	//------------------------------------------------------------------------------------------------------------------
	GetAuditLogs(ctx context.Context) ([]AuditLog, error)
	GetAuditLogsForTarget(ctx context.Context, arg GetAuditLogsForTargetParams) ([]AuditLog, error)
	GetCloudTenant(ctx context.Context, arg GetCloudTenantParams) (CloudTenant, error)
	GetCloudTenants(ctx context.Context) ([]CloudTenant, error)
	GetGroup(ctx context.Context, id uuid.UUID) (Group, error)
	GetGroupCount(ctx context.Context) (int64, error)
	//------------------------------------------------------------------------------------------------------------------
	// Membership
	//------------------------------------------------------------------------------------------------------------------
	GetGroupMembership(ctx context.Context, groupID uuid.UUID) ([]GetGroupMembershipRow, error)
	GetGroupMembershipForUser(ctx context.Context, arg GetGroupMembershipForUserParams) (GetGroupMembershipForUserRow, error)
	//------------------------------------------------------------------------------------------------------------------
	// Groups
	//------------------------------------------------------------------------------------------------------------------
	GetGroups(ctx context.Context, arg GetGroupsParams) ([]Group, error)
	//------------------------------------------------------------------------------------------------------------------
	// Organizational Units
	//------------------------------------------------------------------------------------------------------------------
	GetOrganizationalUnitChildren(ctx context.Context, parentID uuid.NullUUID) ([]OrganizationalUnit, error)
	GetOrganizationalUnitCloudAccounts(ctx context.Context, organizationalUnitID uuid.UUID) ([]CloudAccount, error)
	GetOrganizationalUnits(ctx context.Context) ([]OrganizationalUnit, error)
	//------------------------------------------------------------------------------------------------------------------
	// Tags
	//------------------------------------------------------------------------------------------------------------------
	GetTags(ctx context.Context) ([]StandardTag, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserCount(ctx context.Context) (int64, error)
	GetUserOrganizationalUnits(ctx context.Context, userID uuid.UUID) ([]OrganizationalUnit, error)
	//------------------------------------------------------------------------------------------------------------------
	// Users
	//------------------------------------------------------------------------------------------------------------------
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
	GetUsersById(ctx context.Context, dollar_1 []uuid.UUID) ([]User, error)
	//------------------------------------------------------------------------------------------------------------------
	// SCIM API Key
	//------------------------------------------------------------------------------------------------------------------
	InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error)
	InsertScimAPIKey(ctx context.Context, apiKeyID uuid.UUID) (ScimApiKey, error)
	OrganizationalUnitsCloudAccounts(ctx context.Context, dollar_1 []uuid.UUID) ([]CloudAccount, error)
	PatchGroupDisplayName(ctx context.Context, arg PatchGroupDisplayNameParams) error
	PatchUser(ctx context.Context, arg PatchUserParams) error
	//------------------------------------------------------------------------------------------------------------------
	// Cloud Accounts
	//------------------------------------------------------------------------------------------------------------------
	SearchTag(ctx context.Context, arg SearchTagParams) ([]CloudAccount, error)
	UnAssignAccountFromOUs(ctx context.Context, cloudAccountID uuid.UUID) error
	UpdateCloudAccount(ctx context.Context, arg UpdateCloudAccountParams) error
	UpdateCloudAccountTagsDriftDetected(ctx context.Context, arg UpdateCloudAccountTagsDriftDetectedParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
