apiVersion:  skaffold/v2beta28
kind: Config
metadata:
  name: skyscrapper-web
#requires:
#  - path: ../skyscrapper-server
#    git:
#      repo: https://github.com/suse-skyscraper/skyscraper-server
#      path: .
#      ref: master
#      sync: false
build:
  local:
    push: false
  artifacts:
    - image: skyscraper-web
      context: .
deploy:
  kubectl:
    manifests:
      - kubernetes/config.yaml
      - kubernetes/deployment.yaml
