apiVersion:  skaffold/v2beta28
kind: Config
metadata:
  name: skyscraper-config
deploy:
  kubectl:
    manifests:
      - kubernetes/config/gen/skyscraper-server-tls.yaml
      - kubernetes/config/gen/skyscraper-server-config.yaml
      - kubernetes/config/gen/skyscraper-web-tls.yaml
      - kubernetes/config/gen/skyscraper-web-config.yaml
---
apiVersion:  skaffold/v2beta28
kind: Config
metadata:
  name: skyscraper-web
build:
  local:
    push: false
  artifacts:
    - image: skyscraper-web
      context: .
      docker:
        dockerfile: docker/skyscraper-web.Dockerfile
    - image: skyscraper-server
      context: .
      docker:
        dockerfile: docker/skyscraper-server.Dockerfile
deploy:
  helm:
    releases:
      - name: nats
        remoteChart: nats/nats
        version: 0.17.1
        valuesFiles:
          - kubernetes/helm/nats-values.yaml
      - name: postgres
        remoteChart: bitnami/postgresql
        version: 11.6.10
        valuesFiles:
          - kubernetes/helm/postgresql-values.yaml
      - name: skyscraper-web
        #chartPath: ../skyscraper-helm-charts/charts/skyscraper
        remoteChart: skyscraper/skyscraper
        version: 0.1.5
        valuesFiles:
          - kubernetes/helm/skyscraper-values.yaml
        artifactOverrides:
          skyscraper_web.image.name: skyscraper-web
          skyscraper_server.image.name: skyscraper-server
