// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"time"

	"github.com/jackc/pgtype"
)

type CloudAccount struct {
	Cloud             string
	TenantID          string
	AccountID         string
	Name              string
	Active            bool
	TagsCurrent       pgtype.JSONB
	TagsDesired       pgtype.JSONB
	TagsDriftDetected bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type CloudTenant struct {
	Cloud     string
	TenantID  string
	Name      string
	Active    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
