// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type CloudAccount struct {
	Cloud             string
	TenantID          string
	AccountID         string
	Name              string
	Active            bool
	TagsCurrent       pgtype.JSONB
	TagsDesired       pgtype.JSONB
	TagsDriftDetected bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type CloudTenant struct {
	Cloud     string
	TenantID  string
	Name      string
	Active    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Group struct {
	ID          uuid.UUID
	DisplayName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GroupMember struct {
	ID        int32
	GroupID   uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Policy struct {
	ID    uuid.UUID
	Ptype string
	V0    string
	V1    string
	V2    sql.NullString
	V3    sql.NullString
	V4    sql.NullString
	V5    sql.NullString
}

type ScimApiKey struct {
	ID        uuid.UUID
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID          uuid.UUID
	Username    string
	ExternalID  sql.NullString
	Name        pgtype.JSONB
	DisplayName sql.NullString
	Locale      sql.NullString
	Active      bool
	Emails      pgtype.JSONB
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
