// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"time"

	"github.com/jackc/pgtype"
)

type CloudAccount struct {
	Cloud             string
	TenantID          string
	AccountID         string
	Name              string
	Active            bool
	TagsCurrent       pgtype.JSONB
	TagsDesired       pgtype.JSONB
	TagsDriftDetected bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type CloudTenant struct {
	Cloud     string
	TenantID  string
	Name      string
	Active    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Group struct {
	ID          int32
	DisplayName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GroupMember struct {
	ID        int32
	GroupID   int32
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int32
	Username  string
	Name      pgtype.JSONB
	Active    bool
	Emails    pgtype.JSONB
	CreatedAt time.Time
	UpdatedAt time.Time
}
