// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	//------------------------------------------------------------------------------------------------------------------
	// Cloud Tenants
	//------------------------------------------------------------------------------------------------------------------
	CreateCloudTenant(ctx context.Context, arg CreateCloudTenantParams) error
	//------------------------------------------------------------------------------------------------------------------
	// Cloud Account Metadata
	//------------------------------------------------------------------------------------------------------------------
	CreateOrInsertCloudAccount(ctx context.Context, arg CreateOrInsertCloudAccountParams) (CloudAccount, error)
	GetCloudAccount(ctx context.Context, arg GetCloudAccountParams) (CloudAccount, error)
	GetCloudAllAccounts(ctx context.Context) ([]CloudAccount, error)
	GetCloudAllAccountsForCloud(ctx context.Context, cloud string) ([]CloudAccount, error)
	GetCloudAllAccountsForCloudAndTenant(ctx context.Context, arg GetCloudAllAccountsForCloudAndTenantParams) ([]CloudAccount, error)
	GetCloudTenant(ctx context.Context, arg GetCloudTenantParams) (CloudTenant, error)
	GetCloudTenants(ctx context.Context) ([]CloudTenant, error)
	UpdateCloudAccount(ctx context.Context, arg UpdateCloudAccountParams) error
	UpdateCloudAccountTagsDriftDetected(ctx context.Context, arg UpdateCloudAccountTagsDriftDetectedParams) error
}

var _ Querier = (*Queries)(nil)
