openapi: 3.0.3
info:
  title: Skyscraper
  description: Skyscraper
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /healthz:
    get:
      description: Health check
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
  /api/v1/profile:
    get:
      description: Returns the user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/UserResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/cloud_tenants:
    get:
      description: Returns the cloud tenants
      security:
        - bearerAuth: []
      responses:
        '200':
          description: The cloud tenants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CloudTenant'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/tags:
    post:
      description: Creates a tag
      security:
        - bearerAuth: []
      requestBody:
        $ref: '#/components/requestBodies/CreateTagRequest'
      responses:
        '201':
          $ref: '#/components/responses/TagResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
    get:
      description: Returns the tags
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/TagsResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/tags/{id}:
    put:
      description: Creates a tag
      parameters:
        - name: id
          in: path
          description: The tag ID
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        $ref: '#/components/requestBodies/UpdateTagRequest'
      responses:
        '200':
          $ref: '#/components/responses/TagResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/cloud_tenants/cloud/{cloud}/tenant/{tenant_id}/accounts:
    get:
      description: Returns the accounts for a cloud tenant
      security:
        - bearerAuth: []
      parameters:
        - name: cloud
          in: path
          description: The cloud provider name
          required: true
          schema:
            type: string
        - name: tenant_id
          in: path
          description: The tenant ID
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/AccountsResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/cloud_tenants/cloud/{cloud}/tenant/{tenant_id}/accounts/{id}:
    put:
      description: Updates an account for a cloud tenant
      security:
        - bearerAuth: []
      parameters:
        - name: cloud
          in: path
          description: The cloud provider name
          required: true
          schema:
            type: string
        - name: tenant_id
          in: path
          description: The tenant ID
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: The account ID
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/UpdateAccountRequest'
      responses:
        '200':
          $ref: '#/components/responses/AccountResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
    get:
      description: Returns the account for a cloud tenant
      security:
        - bearerAuth: []
      parameters:
        - name: cloud
          in: path
          description: The cloud provider name
          required: true
          schema:
            type: string
        - name: tenant_id
          in: path
          description: The tenant ID
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: The account ID
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/AccountResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
components:
  requestBodies:
    CreateTagRequest:
      description: To update a tag
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  display_name:
                    type: string
                  key:
                    type: string
                  required:
                    type: boolean
                  description:
                    type: string
    UpdateTagRequest:
      description: To update a tag
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  display_name:
                    type: string
                  key:
                    type: string
                  required:
                    type: boolean
                  description:
                    type: string
    UpdateAccountRequest:
      description: The account update request body
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  tags_desired:
                    type: object
  responses:
    BadRequestError:
      description: Bad request
    UnauthorizedError:
      description: Access token is missing or invalid
    InternalError:
      description: An unexpected internal error occurred
    AccountsResponse:
      description: The accounts
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Account'

    AccountResponse:
      description: The account
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/Account'
    UserResponse:
      description: The user
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/User'
    TagResponse:
      description: The Tag
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/Tag'
    TagsResponse:
      description: The Tags
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        data:
          type: object
          required:
            - id
            - type
          properties:
            id:
              type: string
            type:
              type: string
            attributes:
              type: object
              required:
                - username
              properties:
                username:
                  type: string
                locale:
                  type: string
                active:
                  type: boolean
                created_at:
                  type: string
                updated_at:
                  type: string
    CloudTenant:
      type: object
      properties:
        cloud_provider:
          type: string
        tenant_id:
          type: string
        name:
          type: string
        active:
          type: boolean
        created_at:
          type: string
        updated_at:
          type: string
    Tag:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        attributes:
          type: object
          properties:
            display_name:
              type: string
            description:
              type: string
            required:
              type: boolean
            key:
              type: string
    Account:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        attributes:
          type: object
          properties:
            cloud_provider:
              type: string
            tenant_id:
              type: string
            account_id:
              type: string
            name:
              type: string
            tags_current:
              type: object
              additionalProperties:
                type: string
            tags_desired:
              type: object
              additionalProperties:
                type: string
            tags_drift_detected:
              type: boolean
            active:
              type: boolean
            created_at:
              type: string
            updated_at:
              type: string
security:
  - bearerAuth: []
