openapi: 3.0.3
info:
  title: Skyscraper
  description: Skyscraper
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /healthz:
    get:
      description: Health check endpoint
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
  /api/v1/profile:
    get:
      description: Returns the user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/UserResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/users:
    get:
      description: Returns the list of users
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          $ref: '#/components/responses/UsersResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/users/{id}:
    get:
      description: Returns the user with the given id
      parameters:
        - name: id
          in: path
          description: The account ID
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/UserResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/audit_logs:
    get:
      description: Returns the audit logs
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: resource_id
          description: The id of the resource to filter the audit logs by
          required: false
          schema:
            type: string
        - in: query
          name: resource_type
          description: The type of the resource to filter the audit logs by
          required: false
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/AuditLogsResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/cloud_tenants:
    get:
      description: Returns the cloud tenants
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/CloudTenantsResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/cloud_accounts:
    get:
      description: Returns the list of cloud accounts
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/CloudAccountsResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/cloud_accounts/{id}:
    put:
      description: Updates an account for a cloud tenant
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          description: The account ID
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/UpdateAccountRequest'
      responses:
        '200':
          $ref: '#/components/responses/CloudAccountResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
    get:
      description: Returns the account for a cloud tenant
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          description: The account ID
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/CloudAccountResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/tags:
    post:
      description: Creates a tag
      security:
        - bearerAuth: []
      requestBody:
        $ref: '#/components/requestBodies/CreateTagRequest'
      responses:
        '201':
          $ref: '#/components/responses/TagResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
    get:
      description: Returns the tags
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/TagsResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/tags/{id}:
    put:
      description: Creates a tag
      parameters:
        - name: id
          in: path
          description: The tag ID
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        $ref: '#/components/requestBodies/UpdateTagRequest'
      responses:
        '200':
          $ref: '#/components/responses/TagResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalError'
components:
  requestBodies:
    CreateTagRequest:
      description: To update a tag
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  display_name:
                    type: string
                  key:
                    type: string
                  required:
                    type: boolean
                  description:
                    type: string
    UpdateTagRequest:
      description: To update a tag
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  display_name:
                    type: string
                  key:
                    type: string
                  required:
                    type: boolean
                  description:
                    type: string
    UpdateAccountRequest:
      description: The account update request body
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  tags_desired:
                    type: object
  responses:
    BadRequestError:
      description: Bad request
    UnauthorizedError:
      description: Access token is missing or invalid
    InternalError:
      description: An unexpected internal error occurred
    CloudTenantsResponse:
      description: A response containing the cloud tenants
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/CloudTenant'
    AuditLogsResponse:
      description: A response containing the audit logs
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/AuditLog'
              included:
                type: array
                items:
                  $ref: '#/components/schemas/Included'
    CloudAccountsResponse:
      description: A response containing the list of accounts
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/CloudAccount'
    CloudAccountResponse:
      description: A response containing the account
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/CloudAccount'
    UsersResponse:
      description: A response containing a list of users
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    UserResponse:
      description: A response containing a user
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/User'
    TagResponse:
      description: A response containing a tag
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/Tag'
    TagsResponse:
      description: A response containing a list of tags
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    AuditLog:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
            type:
              type: string
            attributes:
              type: object
              properties:
                created_at:
                  type: string
                updated_at:
                  type: string
                user_id:
                  type: string
                resource_id:
                  type: string
                resource_type:
                  type: string
                message:
                  type: string
            relationships:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string

    Included:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        attributes:
          type: object
    User:
      type: object
      properties:
        data:
          type: object
          required:
            - id
            - type
          properties:
            id:
              type: string
            type:
              type: string
            attributes:
              type: object
              required:
                - username
              properties:
                username:
                  type: string
                locale:
                  type: string
                active:
                  type: boolean
                created_at:
                  type: string
                updated_at:
                  type: string
    CloudTenant:
      type: object
      properties:
        cloud_provider:
          type: string
        tenant_id:
          type: string
        name:
          type: string
        active:
          type: boolean
        created_at:
          type: string
        updated_at:
          type: string
    Tag:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        attributes:
          type: object
          properties:
            display_name:
              type: string
            description:
              type: string
            key:
              type: string
    CloudAccount:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        attributes:
          type: object
          properties:
            cloud_provider:
              type: string
            tenant_id:
              type: string
            account_id:
              type: string
            name:
              type: string
            tags_current:
              type: object
              additionalProperties:
                type: string
            tags_desired:
              type: object
              additionalProperties:
                type: string
            tags_drift_detected:
              type: boolean
            active:
              type: boolean
            created_at:
              type: string
            updated_at:
              type: string
security:
  - bearerAuth: []
