name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      jetstream:
        image: nats:alpine
        options: --name jetstream
        ports:
          - "4222:4222"
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
    steps:
      - uses: actions/checkout@v3

      - name: start_jetstream
        run: |
          docker cp ${{ github.workspace }}/.github/test-config/nats-entrypoint.sh jetstream:/usr/local/bin/docker-entrypoint.sh
          docker restart jetstream

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        if: ${{ github.ref != 'refs/heads/master' }}
        with:
          version: latest
          args: -E gofmt

      - name: Build
        run: make build

      - name: Configure Tests
        run: |
          cp ${{ github.workspace }}/.github/test-config/config.yaml .
          go run ./cli/cmd/main.go migrate up

      - name: Test
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          name: go-coverage
